a = input('Digite uma palavra aqui: ')
print(f'o tipo primitivo desse valor é {type(a)} ')
print(f'Esse valor é minusculo? {a.islower()} ')
print(f'Esse valor é alfanumérico? {a.isalnum()} ')
print(f'Esse valor é maisuculo? {a.isupper()} ')
print(f'esse valor é gravavel? {a.isprintable()} ')
print(f'Esse valor é um número? {a.isnumeric()} ')
print(f'Esse valor é alfabético? {a.isalpha()} ')
print(f'Esse valor está capitalizado? {a.istitle()} ')
